version: '3.3'

services:
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=prueba_inlaze
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data:
